import { QRTemplate } from '../types/qr';

export const PRESET_TEMPLATES: QRTemplate[] = [
  {
    id: 'classic-dark',
    name: 'Classic Dark',
    description: 'Clean high-contrast black & white style for maximum reliability.',
    previewBg: 'bg-slate-900',
    customization: {
      foregroundColor: '#0f172a',
      backgroundColor: '#ffffff',
      useGradient: false,
      gradientType: 'linear',
      gradientColor: '#3b82f6',
      dotStyle: 'square',
      eyeFrameStyle: 'square',
      eyeDotStyle: 'square',
      eyeOuterColor: '#0f172a',
      eyeInnerColor: '#0f172a',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    description: 'Futuristic purple-to-indigo gradient with rounded dots.',
    previewBg: 'bg-indigo-950',
    customization: {
      foregroundColor: '#6366f1',
      backgroundColor: '#ffffff',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#a855f7',
      dotStyle: 'rounded',
      eyeFrameStyle: 'rounded',
      eyeDotStyle: 'rounded',
      eyeOuterColor: '#4f46e5',
      eyeInnerColor: '#9333ea',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'Q',
    },
  },
  {
    id: 'royal-emerald',
    name: 'Royal Emerald',
    description: 'Sophisticated deep emerald green with elegant circle eyes.',
    previewBg: 'bg-emerald-950',
    customization: {
      foregroundColor: '#047857',
      backgroundColor: '#f0fdf4',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#065f46',
      dotStyle: 'classy',
      eyeFrameStyle: 'circle',
      eyeDotStyle: 'circle',
      eyeOuterColor: '#047857',
      eyeInnerColor: '#064e3b',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'Q',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm coral and amber tones with extra rounded modules.',
    previewBg: 'bg-rose-950',
    customization: {
      foregroundColor: '#e11d48',
      backgroundColor: '#fff1f2',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#d97706',
      dotStyle: 'extra-rounded',
      eyeFrameStyle: 'rounded',
      eyeDotStyle: 'circle',
      eyeOuterColor: '#be123c',
      eyeInnerColor: '#b45309',
      logoSize: 0.22,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'H',
    },
  },
  {
    id: 'minimal-dots',
    name: 'Minimal Dots',
    description: 'Ultra-modern dotted matrix with sleek inner eye accents.',
    previewBg: 'bg-slate-900',
    customization: {
      foregroundColor: '#1e293b',
      backgroundColor: '#f8fafc',
      useGradient: false,
      gradientType: 'linear',
      gradientColor: '#0f172a',
      dotStyle: 'dots',
      eyeFrameStyle: 'rounded',
      eyeDotStyle: 'rounded',
      eyeOuterColor: '#0f172a',
      eyeInnerColor: '#2563eb',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'corporate-blue',
    name: 'Corporate Blue',
    description: 'Professional navy blue design trusted by modern brands.',
    previewBg: 'bg-blue-950',
    customization: {
      foregroundColor: '#1e40af',
      backgroundColor: '#eff6ff',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#1d4ed8',
      dotStyle: 'rounded',
      eyeFrameStyle: 'square',
      eyeDotStyle: 'square',
      eyeOuterColor: '#1e3a8a',
      eyeInnerColor: '#1d4ed8',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'Q',
    },
  },
  {
    id: 'vintage-gold',
    name: 'Vintage Gold',
    description: 'Luxury gold metallic aesthetic with high-end eye details.',
    previewBg: 'bg-amber-950',
    customization: {
      foregroundColor: '#b45309',
      backgroundColor: '#fffbeb',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#78350f',
      dotStyle: 'classy',
      eyeFrameStyle: 'circle',
      eyeDotStyle: 'circle',
      eyeOuterColor: '#92400e',
      eyeInnerColor: '#78350f',
      logoSize: 0.22,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'H',
    },
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Refreshing cyan-blue gradient with soft rounded corners.',
    previewBg: 'bg-cyan-950',
    customization: {
      foregroundColor: '#0891b2',
      backgroundColor: '#ecfeff',
      useGradient: true,
      gradientType: 'linear',
      gradientColor: '#2563eb',
      dotStyle: 'extra-rounded',
      eyeFrameStyle: 'circle',
      eyeDotStyle: 'rounded',
      eyeOuterColor: '#0e7490',
      eyeInnerColor: '#1d4ed8',
      logoSize: 0.2,
      logoMargin: 2,
      quietZone: 2,
      errorCorrectionLevel: 'Q',
    },
  },
];
